name: UnitTest

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
    - name: Install system dependencies
      run: |
        sudo apt-get update && sudo apt-get install -y python3-dbus libdbus-glib-1-dev
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run mypy
      run: |
        python -m mypy Nodes --disallow-untyped-calls --ignore-missing-imports
	python -m mypy Server --disallow-untyped-calls --ignore-missing-imports
    - name: Run pytest
      run: |
        python -m pip install pytest
        PYTHONPATH=. python3 -m pytest
